---
layout: cv
title: My CV
---
# Kona Keawekane
Student of BYU-Idaho, Programmer

<div id="webaddress">
    konakeawekane@gmail.com
</div>


## About Me

I am a student currently enrolled in BYU-Idaho studying computer science. I love cars, RC, sports, and computer programming, however most important to me is the gospel of Jesus Christ and my family. I have come to appreciate the growth and development of computing technology over the years and have grown a personal drive to continue innovating on what can be done with computers. I constantly seek to do things that have never been done before and improve upon the status quo. In several of my own projects I have taken an iterative approach to consistently improve and build better and more capable programs.

### Experience

- Full-Time Missionary
    - (The Church of Jesus Christ of Latter-Day Saints)
- Eagle Scout
    - (Boy Scouts of America)

### Skills

- Computer Programming
    - (Javascript, python, rust, HTML, CSS, C#)
- 3D modeling
    - (blender)
- Game Development
    - (Unreal Engine 4-5, Unity, Godot, Flax)


### Projects

- Stochastic Viewspace Global Illumination
    - (Inspired by this paper: <a href="https://dl.acm.org/doi/10.1145/3451268">https://dl.acm.org/doi/10.1145/3451268</a>)
    - <a href="https://konakeawekane.github.io/Stochastic-Cubemap-Global-Illumination">https://konakeawekane.github.io/Stochastic-Cubemap-Global-Illumination</a>

- Clay 3D 
    - (A web based 3D game engine with documentation built mostly with Google's Gemini 3 pro)
    - <a href="https://konakeawekane.github.io/Clay-3D/">https://konakeawekane.github.io/Clay-3D/</a>

- Web Audio Spatialization Renderer
    - (Tool for modeling Acoustic effects of 3D environments on sound files)
    - <a href="https://konakeawekane.github.io/Audio-Spatialization-Renderer/">https://konakeawekane.github.io/Audio-Spatialization-Renderer/</a>

- Custom extensions for the scratch editor 
    - (Integration for compute shaders, Integration for Web Audio API)
    - <a href="https://github.com/konakeawekane/scratch-extentions">https://github.com/konakeawekane/scratch-extentions</a>

- Dream Car
    - (Small web game emphasizing creativity and limitless creation)
    - <a href="https://github.com/konakeawekane/Dream-Car">https://github.com/konakeawekane/Dream-Car</a>

- Rust CPU 3D Graphics 
    - (current educational project)
    - <a href="https://github.com/konakeawekane/my_engine">https://github.com/konakeawekane/my_engine</a>

<!-- ### Footer

Last updated: May 2013 -->